vich_uploader:
    db_driver: orm

    mappings:
        hotel_image:
            uri_prefix: /images/hotels
            upload_destination: '%kernel.project_dir%/public/images/hotels'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
