vich_uploader:
    db_driver: orm
    mappings:
        topic_image:
            uri_prefix: /images/topics
            upload_destination: '%kernel.project_dir%/public/images/topics'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        sujet_image:
            uri_prefix: /images/sujet
            upload_destination: '%kernel.project_dir%/public/images/sujet'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
